version: "3.9"

services:
  mq:
    image: rabbitmq:3.13-management
    container_name: mq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # RabbitMQ UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  consulta-proxy:
    build: ./proxy
    container_name: consulta-proxy
    depends_on:
      - mq
    environment:
      # Rabbit
      AMQP_URL: "amqp://guest:guest@mq:5672/%2F"
      EXCHANGE: "inventory.ex"
      RK_QUERY: "inventory.query"

      # Tiempo total para esperar respuesta del worker (seg)
      RPC_TIMEOUT: "2"

      # Logs y caché
      LOG_PATH: "/var/log/consulta/proxy.jsonl"
      CACHE_FILE: "/var/cache/consulta/last_good.json"

      # Puerto HTTP interno del contenedor
      PORT: "80"
    volumes:
      - ./logs:/var/log/consulta
      - ./cache:/var/cache/consulta
    ports:
      - "8080:80"   # Exponemos el proxy en localhost:8080

  consulta-worker:
    build: ./worker
    container_name: consulta-worker
    depends_on:
      - mq
    environment:
      AMQP_URL: "amqp://guest:guest@mq:5672/%2F"
      EXCHANGE: "inventory.ex"
      QUEUE_MAIN: "inventory.q"
      RK_QUERY: "inventory.query"
      QUEUE_RETRY_2S: "inventory.retry.2s"
      RK_RETRY: "inventory.retry"

      # Reintentos (totales, contando el primer intento=0)
      MAX_RETRIES: "2"

      # Timeout de la llamada al upstream (seg)
      UPSTREAM_TIMEOUT: "1.8"

      # URL del upstream real
      UPSTREAM_URL: "https://maestria.codezor.dev/consulta"

      LOG_PATH: "/var/log/consulta/worker.jsonl"
      CACHE_FILE: "/var/cache/consulta/last_good.json"
    volumes:
      - ./logs:/var/log/consulta
      - ./cache:/var/cache/consulta

  consulta-monitor:
    build: ./monitor
    container_name: consulta-monitor
    environment:
      OUT_DIR: "/var/log/consulta"
      STATE_FILE: "/var/cache/consulta/monitor_state.json"
      UPSTREAM_HEALTH_URL: "https://maestria.codezor.dev/health"
      FAIL_THRESHOLD: "3"
      FAIL_WINDOW: "5"
      INTERVAL_SECONDS: "1"
    volumes:
      - ./logs:/var/log/consulta
      - ./cache:/var/cache/consulta
